### ISSUE TITLE
HELP，HELP, HELP

### ISSUE THREAD

**Issue by Lu-Shen** [gtato/ChordSim#1]
Can you tell me how to run this simulation system? Thank you.

**Comment by gtato** [comment]
I hope you are familiar with PeerSim simulator (http://peersim.sourceforge.net/). 
First you need to download the PeerSim libraries (from here https://sourceforge.net/projects/peersim/) and import them to your project.
You need djep-1.0.0.jar, jep-2.3.0.jar and peersim-1.0.5.jar.

Once you got that and you have imported the ChordSim code to your project, it should compile without errors. 
In order to run it, you have to configure the "Run configurations". In "Main class" you need to put "peersim.Simulator".
While in the program arguments (second tab), you need to put the name of the configuration file, which in this case is chord.cfg.

Please don't open issues for things like this!
